[package]
name = "kanopy"
version = "0.1.0"
edition = "2021"
authors = [
    "Fyra Labs",
    "Pornpipat Popum <cappy@fyralabs.com>",
    "Lleyton Gray <lea@fyralabs.com>",
]
license = "GPL-3.0"
description = "A CLI tool for managing Kanopy Clusters"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.3", features = ["env", "derive"] }
color-eyre = "0.6.2"
rand = "0.8.5"
serde = { version = "1.0.164", features = ["serde_derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
tempfile = "3.6.0"
templar = "0.5.0"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["tracing", "serde"] }
